server:
  port: 8081
  servlet:
    context-path: /
  address: 0.0.0.0

spring:
  application:
    name: demo
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration

# Logging config
logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: WARN
    org.springframework.boot: WARN
    org.hibernate: WARN
    com.gshmalyukh: INFO
