CREATE TABLE TREATMENT_PLANS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    TREATMENT_ACTION TINYINT NOT NULL,
    PATIENT VARCHAR(255) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    RECURRENCE_PATTERN VARCHAR(255) NOT NULL
);

CREATE TABLE TREATMENT_TASKS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    TREATMENT_PLAN BIGINT,
    TREATMENT_ACTION TINYINT NOT NULL,
    PATIENT VARCHAR(255) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    TREATMENT_STATUS TINYINT NOT NULL,
    FOREIGN KEY (TREATMENT_PLAN) REFERENCES TREATMENT_PLANS(id)
);

CREATE UNIQUE INDEX TASKS_UNIQUE_IDX ON TREATMENT_TASKS (TREATMENT_PLAN, START_TIME, TREATMENT_STATUS);